baseURL= "http://blazickjp.github.io"
publishDir= "docs"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Joseph Blazick"
theme = "anatole"
summarylength = 100
enableEmoji = true
enableRobotsTXT = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
[params]
  author = "Joseph Blazick"
  description = "Call me Joe"
  doNotLoadAnimations = "no"
  favicon = "favicons/"
  images = "images/site-feature-image.png"
  keywords = ''
  mainSections = "post"
  profilePicture = "images/joe2.jpg"
[[params.social]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/joe-blazick-119307a2/"
[[params.social]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/blazickjp"
[[params.social]]
  icon = "fas fa-envelope"
  title = "e-mail"
  url = "mailto:joe.blazick@yahoo.com"
[[menu.main]]
  title = "I'm Joseph Blazick"
  name = "Home"
  url = "/"
  weight = 200
[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 200
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 200
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 400
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "kate"
    tabWidth = 4
