baseURL: http://blazickjp.github.io
publishDir: docs
languageCode: en
DefaultContentLanguage: en
title: Website of Joseph Blazick
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Joseph Blazick
  customCss: []
  customJs: []
  description: Call me Joe
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: yes
    use: mathjax
  profilePicture: images/profile.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://de.linkedin.com/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/lxndrblz/anatole/
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:mail@example.com
  title: I'm Joseph Blazick
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
