baseURL: http://blazickjp.github.io
publishDir: docs
languageCode: en
DefaultContentLanguage: en
title: Website of Joseph Blazick
theme: anatole
summarylength: 100
enableEmoji: true
enableRobotsTXT: true
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
params:
  author: Joseph Blazick
  customCss: []
  customJs: []
  description: Call me Joe
  doNotLoadAnimations: false
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: true
  profilePicture: images/joe2.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/joe-blazick-119307a2/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/blazickjp
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:joe.blazick@yahoo.com
  title: I'm Joseph Blazick
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
